### ISSUE TITLE
Installing Gems During Bootstrap

### ISSUE THREAD

**Issue by mitchelldavis** [chef/knife-windows#119]
I've found that during a bootstrap of a Windows 2008 R2 machine (via Knife-ec2), if the recipe requires a gem and installs it, the bootstrap intermittently fails with a "memory exception".

For example, when we use the `windows_zipFile` resource from the [windows cookbook](https://github.com/opscode-cookbooks/windows) in our recipe, it requires the [rubyzip](https://github.com/rubyzip/rubyzip) gem, which is has to install.  When it attempts to, it fails with a memory exception.  

I've read around and it sounds like installing gems on windows machines is memory intensive, but this seems like such a basic thing that you would want to do in a recipe that it shouldn't fail this easily.  So, I'm forced to think I'm doing something wrong, and I wanted to post this here to see if this is a known issue, and if so, if it has a work around.

I've double checked to make sure that WinrRM is setup correctly in our image, and even upped the max memory in the shell to 1024, instead of the recommended 300.

**Comment by btm** [comment]
@mitchelldavis I don't suppose you're still able to produce this error or now know what caused it?

**Comment by mitchelldavis** [comment]
Thanks for responding @btm 

I actually figured out the issue.  It had to do with the amount of available memory for a winrm process when remoting into a windows machine.

**Comment by btm** [comment]
@mitchelldavis ah, that's what it sounded like. Was it something different than `winrm set winrm/config/winrs @{MaxMemoryPerShellMB="300"}`?

**Comment by mitchelldavis** [comment]
It also had to do with [this](https://support.microsoft.com/en-us/kb/2842230) as well, according to my notes.

**Comment by btm** [comment]
I think WMF3 comes with Server 2012 out of the box. We should probably detect and warn if you're using WMF3 during bootstrap.

**Comment by mitchelldavis** [comment]
Yeah, we started using 2012 R2 instead of 2008 R2 and haven't run into the problem as well.

That's a great idea to push a warning that WMF3 isn't being used would create better visibility into what could *possibly* go wrong.
