### ISSUE TITLE
knife bootstrap run-list role would generate "Missing Cookbook" <...> *roles

### ISSUE THREAD

**Issue by kodayashi** [chef/knife-windows#122]
I've been able to reproduce CHEF-4519 logged back in September 2013 initially logged on chef.opscode.com:

"When attempting to bootstrap a node with a single role listed in the run-list, an error is presented "Missing Cookbook". It appears that if you put a comma at the end of the single role[rolename], the same bootstrap command works."

My environment is as follows:

I've been able to reproduce this same issue. Environment details:
OS: Windows Server 2012 R2
Terminal: Power Shell (run as admin)
ChefDK: v0.3.2
Knife Windows: 0.8.2
Appending the comma after the closing bracket fixes the issue (exactly as detailed in the original bug).

Original ticket: https://tickets.opscode.com/browse/CHEF-4519

**Comment by cheeseplus** [comment]
Closing old resolved issues, please open a new issue with current versions of the software if experiencing the same behaviour.
