### ISSUE TITLE
Bootstrap version is not as predictable compared to bootstrapping linux nodes.

### ISSUE THREAD

**Issue by david-crowder** [chef/knife-windows#131]
With the recent release of client 12 it was brought to my attention that the windows bootstrap command did not act as predictably as its linux counterpart. When bootstrapping a new node the linux template will stay within the same [major release version](https://github.com/opscode/chef/blob/12.0.0/lib/chef/knife/core/bootstrap_context.rb#L135) if no versions are specified (or in older versions would [default to the version doing the bootstrapping](https://github.com/opscode/chef/blob/11.12.8/lib/chef/knife/core/bootstrap_context.rb#L105)). But unless a version is specified in the knife.rb it appears as though the msi template will [always pull latest](https://github.com/opscode/knife-windows/blob/master/lib/chef/knife/bootstrap/windows-chef-client-msi.erb#L111).

Perhaps I am missing something, but as far as I can tell the exact same setup will bootstrap a linux node at 11.12.8, but a windows node at 12.0.1

**Comment by btm** [comment]
knife-windows v0.8.3.rc.0 should fix this. you can install it with ```chef gem install knife-windows --pre```

This is a branch created just to fix this bug based off 0.8.2. I've tested this locally, and as soon as I get some more confirmation that it works for folks I'll release it. /cc @jeremiahsnapp

**Comment by david-crowder** [comment]
Thanks for the update @btm

**Comment by btm** [comment]
knife-windows 0.8.3 has been released: http://lists.opscode.com/sympa/arc/chef/2015-02/msg00154.html
