### ISSUE TITLE
WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server (503) in the middle of bootsrap

### ISSUE THREAD

**Issue by w25r** [chef/knife-windows#143]
When attempting to bootstrap a Windows VM using WinRM from a Windows machine, we've been receiving this error:

10.208.149.188 powershell.exe -ExecutionPolicy Unrestricted -NoProfile -NonInteractive -command "& 'C:\chef\wget.ps1' 'https://www.opscode.com/chef/download?p=windows&pv=2008r2&m=x86_64&v=11.16.4&DownloadContext=PowerShell' 'C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi'"
DEBUG: :relay_output_from_backend => ["10.208.149.188", "Download via PowerShell succeeded.\r\n"]
10.208.149.188 Download via PowerShell succeeded.
DEBUG: :relay_output_from_backend => ["10.208.149.188", "Installing downloaded client package...\r\n\r\nC:\Users\Administrator>msiexec /qn /log \"C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-msi23576.log\" /i \"C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi\" \r\n"]
10.208.149.188 Installing downloaded client package...
10.208.149.188
10.208.149.188 C:\Users\Administrator>msiexec /qn /log "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-msi23576.log" /i "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
ERROR: WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server (503).

It usually fails during the installation of chef, but sometimes that succeeds, and it fails later during a different installation that the recipe is performing.  This seems to have started recently (last few weeks) but I've been unable to get a working state of knife-windows, winrm, etc.

To bootstrap we're simply doing 'knife bootstrap windows winrm' with the ip, credentials, and role passed in.

**Comment by rammulay** [comment]
I get the same error message. 

C:\Users\Administrator>msiexec /qn /log "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-msi22425.log" /i "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
ERROR: WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server (503).

I noticed a couple of things - 1) even though this message indicates an error, the bootstrap and subsequent run_lists complete successfully and 2) I get error message about 3 min after the "Installing downloaded client package..." message.

Any ideas as to what may be causing this?

**Comment by btm** [comment]
@rammulay are you working through a proxy? if not, you should file a separate issue. Please include the version of chef/chefdk, knife-windows, and Windows you are using.

**Comment by rammulay** [comment]
@btm here is some info.
server: Windows Server 2012, using proxy
chef: 12.0.3
knife-windows: gem list knife-windows command does not work for me...says gem: command not found

**Comment by rammulay** [comment]
Any ideas on this issue? There is a 3 minute timeout parameter somewhere that is causing this error message after chef msi starts executing. The fact that the chef msi install goes on to complete and the run_lists converge even after getting this error message tells me that WinRM is being terminated somewhere. The server uses a http proxy but why would that affect the WinRM command? I have increased the winrm config timeout to 1800000 ms as recommended by chef. What else can it be?
