### ISSUE TITLE
winrm/config/service AllowUnencrypted flag is true, but can't connect & error thinks it is false

### ISSUE THREAD

**Issue by philax** [chef/knife-windows#171]
Error: Unencrypted communication not supported. Please check winrm configuration winrm/config/service AllowUnencrypted flag.

Unfortunately, the mentioned flag is already appropriately set: https://gist.github.com/philax/004f0f38426381dcd049 

I'm just running: https://gist.github.com/philax/5434a8917b2ef57c6fab 

I get the same response if I use chef server to search the name instead of -m.

I'm running knife from a windows machine.  gem list | egrep knife-windows returns version 0.8.2.  I've tried in both Powershell and GitBash just in case.

**Comment by siddheshwar-more** [comment]
@philax -
In **knife-windows v0.8.2** - if winrm_user contains domain name and transport is plain text then negotiate protocol is used for encrypted communication. And hence `AllowUnencrypted = true` causes this failure.
Please set `AllowUnencrypted = false` on remote server.

This behavior will change in next knife-windows release.

Thank you!

**Comment by philax** [comment]
Is it actually possible to connect with knife-windows when AllowUnencrypted = false?  I just set it and am getting the following response:

https://gist.github.com/philax/50ac467045c0ab051739

I may have missed it, but all the documentation I've read indicates how to connect with that winrm flag set to true.  I can't seem to find anything indicating there's a method to connect with knife-windows when it is set to false.

**Comment by siddheshwar-more** [comment]
Yes, its possible to connect to remote server by using **knife winrm** when `AllowUnencrypted = false`  by using **sspinegotiate** protocol. 
The knife-windows v0.8.2 has support for **sspinegotiate** transport which does encrypted communication. And v0.8.2 is uses **sspinegotiate** transport when winrm_user contains domain name. 

Can you check your WinRm remote server firewall Inbound Rules (Windows Remote Management(HTTP-In)?

Thank you!

**Comment by philax** [comment]
The remote server firewall is off :)

**Comment by adamedx** [comment]
I don't actually think you can set winrm config from a winrm session -- at least this failed for me in the past.

Firewall is definitely not the issue here.

**Comment by btm** [comment]
@philax did you find a resolution to your issue? The knife-windows 1.0.0.rc.0 prerelease has a much simpler interface for specifying which protocols to use if you'd like to test that out.

**Comment by cheeseplus** [comment]
Closing old resolved issues, please open a new issue with current versions of the software if experiencing the same behaviour.
