### ISSUE TITLE
Encryption issue in workstation os diverse environments

### ISSUE THREAD

**Issue by stevehedrick** [chef/knife-windows#216]
Windows based knife workstations require AllowUnencrypted = false while Linux/OSX requires AllowUnencrypted = true set node-side.

This means no matter the settings, some knife users are unable to connect to some nodes.

When connected to a node allowing unencrypted connections windows nodes respond with:
```
ERROR: RuntimeError: Error: Unencrypted communication not supported. Please check winrm configuration winrm/config/service AllowUnencrypted flag.
```

When connecting to a node forcing encrypted communication OSX/Linux nodes respond with:
```
ERROR: Failed to authenticate to NODE as DOMAIN\USER
Response: Bad HTTP response returned from server (401).
ERROR: WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server (401).
```

Our environment consists of Windows, OSX, & Linux users.  We are attempting to use knife-windows to bootstrap and help manage a series of Windows 2012r2 servers.  Machines are all on the same active directory domain, and the accounts being used to connect to them via knife are all domain based accounts.

We know that we can allow unencrypted connections and it will work on OSX/Linux.  We can also set the encryption on and it will work on Windows.  But there doesn't appear to be a way for it to work with both.  Ideally both would support encryption.

**Comment by btm** [comment]
@stevehedrick Are you using knife-windows 0.8.4 or running building knife-windows yourself out of master? I think it's same either way right now.

We've been trying to make this allow unencrypted situation better for a while. The upcoming release of knife-windows has major authentication refactoring and will default to preferring a secure backchannel (negotiate auth on windows by default). As part of that, I personally want the AllowUnencrypted issue to be improved for reasons similar to what you've described. We're looking into that over on https://github.com/chef/knife-windows/issues/210.

We're hoping that https://github.com/chef/knife-windows/issues/210 will find a way to connect to ```AllowUnencrypted = false``` systems from Windows, which I think is exactly what you want. So I'm going to close this issue and we'll focus on that one for now. Feel welcome to let me know if I missed something though.

**Comment by btm** [comment]
This is being tracked over here now: https://github.com/chef/winrm-s/issues/26
