### ISSUE TITLE
--winrm-authentication-protocol  isnt a valid option

### ISSUE THREAD

**Issue by radiumx3** [chef/knife-windows#217]
--winrm-authentication-protocol  isnt a valid option, how to specify to use kerberos protocol in order to connect with a domain user from a remote AD ?

**Comment by btm** [comment]
What version of knife-windows are you using?

**Comment by btm** [comment]
In knife-windows 0.8 the transport was set to kerberos if you specifed any kerberos configuration options.

https://github.com/chef/knife-windows/blob/0.8.4/lib/chef/knife/winrm.rb#L154
