### ISSUE TITLE
Knife Boostrap Window Network Issue

### ISSUE THREAD

**Issue by dciceman** [chef/knife-windows#226]
I am trying to bootstrap windows server with chef-client and kept getting network issues.

I receive time out messages as such: 
PS E:\user\chef-repo> knife bootstrap windows winrm myip -x "Administrator" -P "Password" -N " somename" --bootstrap-version 11.18.6

Waiting for remote response before bootstrap.......ERROR: No response received from remote node after 2.1 minutes, giving up.
ERROR: Network Error: A connection attempt failed because the connected party did not properly respond after a period of
 time, or established connection failed because connected host has failed to respond. - connect(2) for "xx.xx.xx.xx" port 5985 (http://xx.xx.xx.xx:5985)
Check your knife configuration and network settings

PS I have already executed the following commands on my windows server.

winrm quickconfig -q
winrm set winrm/config/winrs @{MaxMemoryPerShellMB="300"} 
winrm set winrm/config @{MaxTimeoutms="1800000"} 
winrm set winrm/config/service @{AllowUnencrypted="true"}
winrm set winrm/config/service/auth @{Basic="true"}

Chef: 12.3.0
Knife-Windows 0.8.4

**Comment by ac-rmenezes** [comment]
dciceman,


knife bootstrap windows winrm address --winrm-user Administrator --winrm-password ‘Password’

Make winrm start on boot:

net stop winrm
sc config winrm start=auto
net start winrm


Make sure windows firewall isn’t blocking 5985 and you can reach the node (telnet address 5985).
netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in localport=5985 action=allow

You are here already, allow connections to the secure one.
netsh advfirewall firewall add rule name="WinRM 5986" protocol=TCP dir=in localport=5986 action=allow



Regards
Rafael

**Comment by dciceman** [comment]
Thank you Rafael. 
I configured windows firewall port 5985 and 5986. Set winrm start=auto and restarted WinRm. I am still getting the same error.

Telnet errors
C:\Users\administrator>telnet xx.xx.xx.xx 5985
Connecting To xx.xx.xx.xx ...Could not open connection to the host, on port 5985:
Connect failed

More Information about the Server
This is Microsoft Windows Server 2012 R2 RTM 64-bit Locale English AMI provided by Amazon.
I have a public address, but ip config displays private IP address instead. I don't know if it has anything to do with the error. 

Windows IP Configuration
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : ec2.internal
   Link-local IPv6 Address . . . . . : ......
   IPv4 Address. . . . . . . . . . . : 10.0.0.xx
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.0.1

Thanks
David

**Comment by NimishaS** [comment]
@dciceman , seems like firewall is blocking WinRM. Please try the following:
Go to "Windows Firewall" -> Advanced Settings -> Inbound Rules -> Find "Windows Remote Management(HTTP-In) in the Inbound Rules -> Double click on it -> Go to Advanced Tab -> Change the profile to "Public"

**Comment by ac-rmenezes** [comment]
David

> I have a public address, but ip config displays private IP address instead. I don't know if it has anything to do with the error. 
> 

That’s expected - and means that your server is behind a firewall. Have you opened winrm ports via amazon's security groups?

To be sure that winrm and firewall settings on the node are set up properly, try to telnet on the node, using 10.0.0.n ip as the target.


If telnet doesn’t work, its clearly not a Chef issue, though.

Regards
Rafael

**Comment by dciceman** [comment]
Thank you Nimisha and Rafael. I followed both your suggestions and the issues is fixed. 

Details: 
I updated the Windows Remote Management(HTTP-In) in the Inbound Rules to "Public" on the Win 2012 R2 server and I also added inbound TCP with ports 5985 and 5986 into the AWS security group. 

Telnet and bootstrap success.

Thank you for your help.

Thanks,
David
