### ISSUE TITLE
Knife-Windows + Chef-Vault - Support? 

### ISSUE THREAD

**Issue by nhudacin** [chef/knife-windows#237]
I'm using chef vault to pass sensitive data down to our nodes. The knife-bootstrap command supports these parameter switches: 

--bootstrap-vault-file VAULT_FILE
Use to specify the path to a JSON file that contains a list of vaults and items to be updated.
--bootstrap-vault-item VAULT_ITEM
Use to specify a single vault and item to update as vault:item.
--bootstrap-vault-json VAULT_JSON
Use to specify a JSON string that contains a list of vaults and items to be updated.

For those who don't know chef-vault... I have to encrypt the sensitive data using the public key of the client. The workflow using knife-windows seems to be: 

1. Bootstrap node
2. Refresh vault (to get the data encrypted by the new node's public key)
3. Then do the chef run the requires the decrypted sensitive data

The added switches to knife-bootstrap do the above steps during the initial boostrap. It just refreshes the vault before the first chef run on the target node so that the sensitve data is already encrypted using the node's public key before the node tries to access the decrypted information. 

Are these switches supported in knife-windows? Am I missing something? Are others experiencing this same issue and if so how are you managing? 

Thanks!

**Comment by btm** [comment]
These were added in #251 and will be in knife-windows 1.0.0.

**Comment by nhudacin** [comment]
@btm thank you!!

**Comment by btm** [comment]
Any testing would be useful, I'm not sure how much testing this has gotten. I'll ship another RC within a few days, but you could build a gem from master.

**Comment by nhudacin** [comment]
I'll be able to test this no problem when the RC comes out. I'll attempt building this gem from master when I get a chance.
