### ISSUE TITLE
Windows Bootstrap Fails 

### ISSUE THREAD

**Issue by Infydevops** [chef/knife-windows#242]
knife bootstrap windows ssh IP_Address -r 'role[java]' -x Domain/user -i ~/.ssh/id_rsa

Bootstrapping Chef on IP_Address
WARNING: Failed to connect to -- Errno::ETIMEDOUT: A connection at
tempt failed because the connected party did not properly respond after a period
of time, or established connection failed because connected host has failed to

Please let me know in case you need more details around this.

**Comment by btm** [comment]
Are you sure you can ssh to that machine from the one you're on?

Can you run in the command in verbose mode with "-V" specified twice, i.e. `knife bootstrap windows ssh 192.168.1.10 -V -V`?

**Comment by btm** [comment]
@Infydevops, I'm going to close this issue since we haven't heard back from you. Let us know if you're still having issues, or what your resolution was please.
