### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by spuder** [chef/knife-windows#243]
I am running chefdk 5.1. The documentation doesn't say how to install the knife windows plugin. 

I assume that I already have it installed, since `knife winrm` is a valid command. 

Puzzling though, that the commands `knife winsm` is not valid. 

```
** WINDOWS COMMANDS **
knife bootstrap windows winrm FQDN (options)
knife bootstrap windows ssh FQDN (options)
knife winrm QUERY COMMAND (options)

** WINRM COMMANDS **
knife winrm QUERY COMMAND (options)
```

How can you tell if this plugin is installed and How do you install it? I'm happy to make a merge request for the README once I figure this out.

**Comment by btm** [comment]
`chef gem list knife-windows` will tell you what version of knife-windows is in your version of chef-dk. You could install knife-windows into chef-dk with `chef gem install knife-windows`. However, each build meets a certain combination of gem versions so the included dependencies work together, so it is often difficult to replace an older gem in an older version of chef-dk with a much newer version of that gem.

**Comment by btm** [comment]
@spuder I haven't heard back from you so I'm going to close this issue. I'd make sure you're running at least ChefDK 0.6.2. We're going to release ChefDK 0.7.0 soon as well, which will include the newest knife-windows release.
