### ISSUE TITLE
New bootstrap options changes for Chef 12

### ISSUE THREAD

**Issue by Vasu1105** [chef/knife-windows#245]
In chef 12.3.0 there are new bootstrap options added, currently those are not available on knife-windows 
i.e. --bootstrap-install-command, --bootstrap-wget-options, --bootstrap-vault-file, --bootstrap-vault-json, --bootstrap-vault-item 

Ref: https://github.com/chef/chef/commit/2481b6740b6de0ede97574e422dd2980a27b8363
https://github.com/chef/chef/commit/1aa9b128d22a21a39e6d7b7a833538ae3e15929d

**Comment by ksubrama** [comment]
We now have a test that tracks new features that we need to implement.  https://github.com/chef/knife-windows/pull/241

I'll review your change to add vault support shortly.

**Comment by ksubrama** [comment]
Dupe #237

**Comment by Vasu1105** [comment]
@ksubrama I started working on this.

**Comment by ksubrama** [comment]
Sorry for closing this.  @Vasu1105 is using this to track his work.

**Comment by btm** [comment]
Fixed via #251,  will be in knife-windows 1.0.0.
