### ISSUE TITLE
knife bootstrap windows winrm fails on linux with " Connection refused - connect(2) for "windows" port 22"

### ISSUE THREAD

**Issue by fabioxgn** [chef/knife-windows#257]
I'm trying to bootstrap a new server from linux and getting this error (everything is fine on the windows server, I'm able to bootstrap from a windows workstationg).

I'm running this command:

```
knife bootstrap windows winrm <IP> -x <USER> -P <PASSWORD> -N sv7 --bootstrap-version 11.12.8
```

And getting this error:

```
WARNING: Hostname containing 'windows' specified. Please install 'knife-windows' if you are attempting to bootstrap a Windows node via WinRM.
Doing old-style registration with the validation key at /home/fabio/chef-repo/.chef/fabio-validator.pem...
Delete your validation key in order to use your user credentials instead

Connecting to windows
ERROR: Network Error: Connection refused - connect(2) for "windows" port 22
Check your knife configuration and network settings
```

So the questions are:

1. Is bootstraping a windows server from linux supported?
2. I'm I missing something in my command? Looks like it's trying to use SSH instead of winrm

I'm running this from a Docker container, and the Dockerfile I'm using is here:

I installed the knife-windows gem, do I need some aditional step?

Thanks.

```
FROM ubuntu:latest
RUN apt-get -y update && apt-get install -y wget ruby ruby-dev make zlib1g-dev patch g++
RUN wget -O chef.deb https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.4.0-1_amd64.deb
RUN dpkg -i chef.deb
RUN rm chef.deb
RUN gem install knife-windows
RUN mkdir /var/chef
RUN mkdir /var/chef/cache
RUN mkdir /etc/chef
```

**Comment by btm** [comment]
@fabioxgn What does `which gem` return, i.e. is the rubygems installation that you're installing the knife-windows gem the same one that comes in the Chef omnibus installation? You might try `/opt/chef/embedded/bin/gem install knife-windows` instead.

**Comment by fabioxgn** [comment]
@btm that did the trick. Thanks.
