### ISSUE TITLE
Bootstrapping Windows Node Fails: The command line is too long

### ISSUE THREAD

**Issue by mclark1129** [chef/knife-windows#262]
I am attempting to bootstrap a Windows Server 2012 R2 node over WinRM using knife-windows.  The command fails to execute and I am given the message "The command line is too long".  I am using SSL transport, but I have disabled certificate verification for testing purposes.  I am running the command:

`knife bootstrap windows winrm myserver.cloudapp.net -t ssl -p 5986 -x myUsername -P 'myPassword' --winrm-ssl-verify-mode verify_none`

I believe I am running winrm 1.3.3.  That is the version of the gem that is embedded with chefdk.

The result of the highest verbose debug output is:

INFO: Using configuration from C:/users/me/.chef/knife.rb
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate

Waiting for remote response before bootstrap.DEBUG: Looking for key winrm_user and found value myUsername
DEBUG: Looking for key winrm_password and found value myPassword
DEBUG: Looking for key winrm_transport and found value ssl
DEBUG: Looking for key winrm_ssl_verify_mode and found value verify_none
DEBUG: Looking for key kerberos_keytab_file and found value 
DEBUG: Looking for key kerberos_realm and found value 
DEBUG: Looking for key kerberos_service and found value 
DEBUG: Looking for key ca_trust_file and found value 
DEBUG: Looking for key winrm_port and found value 5986
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_user and found value myUsername
DEBUG: Looking for key winrm_password and found value myPassword
DEBUG: Looking for key winrm_port and found value 5986
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value ssl
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Trying WinRM communication with negotiate authentication and :ssl transport
DEBUG: Looking for key ca_trust_file and found value 
DEBUG: Adding myserver.cloudapp.net
DEBUG: WinRM::WinRMWebService options: {:user=>"myUsername", :pass=>"myPassword", :basic_auth_only=>false, :disable_sspi=>true, :no_ssl_peer_verification=>true, :ca_trust_path=>nil}
DEBUG: Endpoint: https://myserver.cloudapp.net:5986/wsman
DEBUG: Transport: ssl
DEBUG: echo . & echo Response received.
DEBUG: myserver.cloudapp.net[2F5FC14D-F890-4F12-8A10-5E6EDAEC32DA] => :run_command[echo . & echo Response received.]
myserver.cloudapp.net . 

myserver.cloudapp.net Response received.

DEBUG: myserver.cloudapp.net[2F5FC14D-F890-4F12-8A10-5E6EDAEC32DA] => :command_cleanup[echo . & echo Response received.]
DEBUG: myserver.cloudapp.net[2F5FC14D-F890-4F12-8A10-5E6EDAEC32DA] => :shell_close
DEBUG: Looking for bootstrap template in C:/Users/me/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap/templates
DEBUG: Looking for bootstrap template in C:/users/me/.chef/bootstrap
DEBUG: Looking for bootstrap template in C:/Users/me/.chef/bootstrap
DEBUG: Looking for bootstrap template in C:/Users/me/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap
DEBUG: Found bootstrap template in C:/Users/me/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap
DEBUG: Looking for key winrm_user and found value myUsername
DEBUG: Looking for key winrm_password and found value myPassword
DEBUG: Looking for key winrm_transport and found value ssl
DEBUG: Looking for key winrm_ssl_verify_mode and found value verify_none
DEBUG: Looking for key kerberos_keytab_file and found value 
DEBUG: Looking for key kerberos_realm and found value 
DEBUG: Looking for key kerberos_service and found value 
DEBUG: Looking for key ca_trust_file and found value 
DEBUG: Looking for key winrm_port and found value 5986
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_user and found value myUsername
DEBUG: Looking for key winrm_password and found value myPassword
DEBUG: Looking for key winrm_port and found value 5986
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value ssl
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Trying WinRM communication with negotiate authentication and :ssl transport
DEBUG: Looking for key ca_trust_file and found value 
DEBUG: Adding myserver.cloudapp.net
DEBUG: WinRM::WinRMWebService options: {:user=>"myUsername", :pass=>"myPassword", :basic_auth_only=>false, :disable_sspi=>true, :no_ssl_peer_verification=>true, :ca_trust_path=>nil}
DEBUG: Endpoint: https://myserver.cloudapp.net:5986/wsman
DEBUG: Transport: ssl
DEBUG: cmd.exe /C echo Rendering "%TEMP%\bootstrap-7196-1436561624.bat" chunk 1 && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Author:: Seth Chisamore ^(^<schisamo@opscode.com^>^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Copyright:: Copyright ^(c^) 2011 Opscode, Inc.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem License:: Apache License, Version 2.0) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Licensed under the Apache License, Version 2.0 ^(the "License"^);) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem you may not use this file except in compliance with the License.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem You may obtain a copy of the License at) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem     http://www.apache.org/licenses/LICENSE-2.0) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Unless required by applicable law or agreed to in writing, software) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem distributed under the License is distributed on an "AS IS" BASIS,) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem See the License for the specific language governing permissions and) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem limitations under the License.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Use delayed environment expansion so that ERRORLEVEL can be evaluated with the) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem !ERRORLEVEL! syntax which evaluates at execution of the line of script, not when) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem the line is read. See help for the /E switch from cmd.exe /? .) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@setlocal ENABLEDELAYEDEXPANSION) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@set BOOTSTRAP_DIRECTORY=C:\chef) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@echo Checking for existing directory "%BOOTSTRAP_DIRECTORY%"...) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@if NOT EXIST %BOOTSTRAP_DIRECTORY% ^() && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@echo Existing directory not found, creating.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@mkdir %BOOTSTRAP_DIRECTORY%) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.^) else ^() && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@echo Existing directory found, skipping creation.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.^> C:\chef\wget.vbs ^() && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.url = WScript.Arguments.Named^^^("url"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.path = WScript.Arguments.Named^^^("path"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.proxy = null) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.'\* Vaguely attempt to handle file:// scheme urls by url unescaping and switching all) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.'\* / into .  Also assume that file:/// is a local absolute path and that file://^^^<foo^^^>) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.'\* is possibly a network file path.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.If InStr^^^(url, "file://"^^^) = 1 Then) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.url = Unescape^^^(url^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.If InStr^^^(url, "file:///"^^^) = 1 Then) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.sourcePath = Mid^^^(url, Len^^^("file:///"^^^) + 1^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.Else) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.sourcePath = Mid^^^(url, Len^^^("file:"^^^) + 1^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.End If) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.sourcePath = Replace^^^(sourcePath, "/", "\"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.Set objFSO = CreateObject^^^("Scripting.FileSystemObject"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.If objFSO.Fileexists^^^(path^^^) Then objFSO.DeleteFile path) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.objFSO.CopyFile sourcePath, path, true)
DEBUG: myserver.cloudapp.net[B6F3AC5C-8EEC-499D-943A-B735631FC10C] => :run_command[cmd.exe /C echo Rendering "%TEMP%\bootstrap-7196-1436561624.bat" chunk 1 && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Author:: Seth Chisamore ^(^<schisamo@opscode.com^>^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Copyright:: Copyright ^(c^) 2011 Opscode, Inc.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem License:: Apache License, Version 2.0) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Licensed under the Apache License, Version 2.0 ^(the "License"^);) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem you may not use this file except in compliance with the License.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem You may obtain a copy of the License at) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem     http://www.apache.org/licenses/LICENSE-2.0) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Unless required by applicable law or agreed to in writing, software) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem distributed under the License is distributed on an "AS IS" BASIS,) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem See the License for the specific language governing permissions and) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem limitations under the License.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Use delayed environment expansion so that ERRORLEVEL can be evaluated with the) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem !ERRORLEVEL! syntax which evaluates at execution of the line of script, not when) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem the line is read. See help for the /E switch from cmd.exe /? .) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@setlocal ENABLEDELAYEDEXPANSION) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@set BOOTSTRAP_DIRECTORY=C:\chef) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@echo Checking for existing directory "%BOOTSTRAP_DIRECTORY%"...) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@if NOT EXIST %BOOTSTRAP_DIRECTORY% ^() && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@echo Existing directory not found, creating.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@mkdir %BOOTSTRAP_DIRECTORY%) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.^) else ^() && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@echo Existing directory found, skipping creation.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.^> C:\chef\wget.vbs ^() && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.url = WScript.Arguments.Named^^^("url"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.path = WScript.Arguments.Named^^^("path"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.proxy = null) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.'\* Vaguely attempt to handle file:// scheme urls by url unescaping and switching all) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.'\* / into .  Also assume that file:/// is a local absolute path and that file://^^^<foo^^^>) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.'\* is possibly a network file path.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.If InStr^^^(url, "file://"^^^) = 1 Then) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.url = Unescape^^^(url^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.If InStr^^^(url, "file:///"^^^) = 1 Then) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.sourcePath = Mid^^^(url, Len^^^("file:///"^^^) + 1^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.Else) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.sourcePath = Mid^^^(url, Len^^^("file:"^^^) + 1^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.End If) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.sourcePath = Replace^^^(sourcePath, "/", "\"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.Set objFSO = CreateObject^^^("Scripting.FileSystemObject"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.If objFSO.Fileexists^^^(path^^^) Then objFSO.DeleteFile path) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.objFSO.CopyFile sourcePath, path, true)]
**myserver.cloudapp.net The command line is too long.**

DEBUG: myserver.cloudapp.net[B6F3AC5C-8EEC-499D-943A-B735631FC10C] => :command_cleanup[cmd.exe /C echo Rendering "%TEMP%\bootstrap-7196-1436561624.bat" chunk 1 && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Author:: Seth Chisamore ^(^<schisamo@opscode.com^>^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Copyright:: Copyright ^(c^) 2011 Opscode, Inc.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem License:: Apache License, Version 2.0) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Licensed under the Apache License, Version 2.0 ^(the "License"^);) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem you may not use this file except in compliance with the License.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem You may obtain a copy of the License at) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem     http://www.apache.org/licenses/LICENSE-2.0) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Unless required by applicable law or agreed to in writing, software) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem distributed under the License is distributed on an "AS IS" BASIS,) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem See the License for the specific language governing permissions and) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem limitations under the License.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem Use delayed environment expansion so that ERRORLEVEL can be evaluated with the) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem !ERRORLEVEL! syntax which evaluates at execution of the line of script, not when) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@rem the line is read. See help for the /E switch from cmd.exe /? .) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@setlocal ENABLEDELAYEDEXPANSION) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@set BOOTSTRAP_DIRECTORY=C:\chef) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@echo Checking for existing directory "%BOOTSTRAP_DIRECTORY%"...) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@if NOT EXIST %BOOTSTRAP_DIRECTORY% ^() && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@echo Existing directory not found, creating.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@mkdir %BOOTSTRAP_DIRECTORY%) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.^) else ^() && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.@echo Existing directory found, skipping creation.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.^> C:\chef\wget.vbs ^() && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.url = WScript.Arguments.Named^^^("url"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.path = WScript.Arguments.Named^^^("path"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.proxy = null) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.'\* Vaguely attempt to handle file:// scheme urls by url unescaping and switching all) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.'\* / into .  Also assume that file:/// is a local absolute path and that file://^^^<foo^^^>) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.'\* is possibly a network file path.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.If InStr^^^(url, "file://"^^^) = 1 Then) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.url = Unescape^^^(url^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.If InStr^^^(url, "file:///"^^^) = 1 Then) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.sourcePath = Mid^^^(url, Len^^^("file:///"^^^) + 1^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.Else) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.sourcePath = Mid^^^(url, Len^^^("file:"^^^) + 1^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.End If) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.sourcePath = Replace^^^(sourcePath, "/", "\"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.Set objFSO = CreateObject^^^("Scripting.FileSystemObject"^^^)) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.If objFSO.Fileexists^^^(path^^^) Then objFSO.DeleteFile path) && >> "%TEMP%\bootstrap-7196-1436561624.bat" (echo.echo.objFSO.CopyFile sourcePath, path, true)]
DEBUG: myserver.cloudapp.net[B6F3AC5C-8EEC-499D-943A-B735631FC10C] => :shell_close

**Comment by hh** [comment]
I'm seeing the same thing over at chef/chef-provisioning#431

**Comment by hh** [comment]
8191 seems to be the max for cmd.exe,but I'm not sure if we are using cmd.exe or powershell

**Comment by siddheshwar-more** [comment]
@NimishaS @hh - 
We have verified with knife windows  WinRM bootstrapping working fine with ssl.

I think this is not the right place for this issue. For this you already created issue at https://github.com/chef/mixlib-install/issues/6. 
Probably we can close this issue from here?

Thank you for pointing this, it will really help us in future.

**Comment by hh** [comment]
Fine with me.

**Comment by cheeseplus** [comment]
Closing old resolved issues, please open a new issue with current versions of the software if experiencing the same behaviour.
