### ISSUE TITLE
Exception: NoMethodError: undefined method `gsub' for false:FalseClass

### ISSUE THREAD

**Issue by rj-reilly** [chef/knife-windows#270]
I see there are other similar errors, and what I understand they were not in the chef-repo dir or do no have a validator.pem.. I have none of these issues, This host was previously bootstrapped and once it was added to the domain the fqdn changed and chef would longer recognize it, here is the output from  -VV and i am running the following:
knife-windows (0.8.5)
em-winrm (0.6.0)
winrm (1.3.3, 1.2.0)
winrm-s (0.2.4)
winrm-transport (1.0.1, 1.0.0)
chefdk 0.6.2

https://gist.github.com/devilldog/b6cdd92beb915ef71685

**Comment by NimishaS** [comment]
@devilldog, can you try with `knife-window master branch`? Fixes mentioned in this comment https://github.com/chef/knife-windows/issues/227#issuecomment-106612351 may fix your problem. `knife-windows` will be released soon.

**Comment by cheeseplus** [comment]
Closing old resolved issues, please open a new issue with current versions of the software if experiencing the same behaviour.
