### ISSUE TITLE
Secret file not being rendered

### ISSUE THREAD

**Issue by asebastian-r7** [chef/knife-windows#271]
When supplying a valid --secret-file it is not written out to c:\chef\encrypted_data_bag_secret. It does not work with a shortcut path (~/.chef/encrypted_data_bag_secret) or full path. Currently I have to copy over the encrypted_data_bag_secret from my local machine to the node. This is using 1.0.0.rc.1

Example command
`knife bootstrap windows winrm 10.0.0.1 --node-name my.node.name --run-list "recipe[nexpose]" --winrm-user Administrator --winrm-password mypassword --secret-file /Users/asebastian/.chef/encrypted_data_bag_secret --winrm-transport ssl`

Output
```txt
10.4.82.141 ================================================================================
10.4.82.141 Recipe Compile Error in c:/chef/cache/cookbooks/nexpose/recipes/node_windows.rb
10.4.82.141 ================================================================================
10.4.82.141
10.4.82.141 ArgumentError
10.4.82.141 -------------
10.4.82.141 No secret specified and no secret found at C:\chef\encrypted_data_bag_secret
10.4.82.141
10.4.82.141 Cookbook Trace:
10.4.82.141 ---------------
10.4.82.141   c:/chef/cache/cookbooks/nexpose/definitions/encrypted_ssh_key_pair.rb:14:in `block in from_file'
10.4.82.141   c:/chef/cache/cookbooks/nexpose/recipes/_node_windows_base.rb:52:in `block in from_file'
10.4.82.141   c:/chef/cache/cookbooks/nexpose/recipes/_node_windows_base.rb:48:in `each'
10.4.82.141   c:/chef/cache/cookbooks/nexpose/recipes/_node_windows_base.rb:48:in `from_file'
10.4.82.141   c:/chef/cache/cookbooks/nexpose/recipes/node_windows.rb:1:in `from_file'
10.4.82.141
```

**Comment by Aliasgar16** [comment]
@asebastian-r7 We are working on this issue.

**Comment by Aliasgar16** [comment]
Refer https://github.com/chef/knife-windows/pull/272 PR for this issue (testing is in progress).

**Comment by Aliasgar16** [comment]
Refer https://github.com/chef/knife-windows/pull/272 PR for the fix.

**Comment by asebastian-r7** [comment]
Thanks for your work on this @Aliasgar16!
