### ISSUE TITLE
WinRM bootstrap  silently fails

### ISSUE THREAD

**Issue by carpnick** [chef/knife-windows#311]
Story:
When trying to move from 0.8.5, to 1.1.0, we noticed the exit code for bootstrapping always succeeded, no matter if bootstrap fails or succeeds.  The knife winrm commands do not have this problem, since a different code path is used, this should also probably be part of the fix for this issue.  winrm/bootstrap should probably share the same basic relay_command code base.  We noticed with the [sample output](https://gist.github.com/carpnick/5486048ee6438734f833) we still got an exit code of 0

Diagnosis so far:
0.8.5
* When bootstrapping this [line](https://github.com/chef/knife-windows/blob/v0.8.5/lib/chef/knife/bootstrap_windows_winrm.rb#L63) gets executed when bootstrapping.
* This maps to [here](https://github.com/chef/knife-windows/blob/v0.8.5/lib/chef/knife/winrm.rb#L269).  If the command fails for any reason(except authentication) it [exits](https://github.com/chef/knife-windows/blob/v0.8.5/lib/chef/knife/winrm.rb#L293)
* Because it exits - it never gets back to [here](https://github.com/chef/knife-windows/blob/v0.8.5/lib/chef/knife/bootstrap_windows_base.rb#L181).  That means the code to return bootstrap_command_result was never being used.

1.1.0
* When bootstrapping this [line](https://github.com/chef/knife-windows/blob/v1.1.0/lib/chef/knife/bootstrap_windows_winrm.rb#L58) get executed.
* It runs then returns the exit code to [here](https://github.com/chef/knife-windows/blob/v1.1.0/lib/chef/knife/bootstrap_windows_base.rb#L323) and the code tries to return the exit code to knife.  Knife drops the return on the floor at this point.
* ASIDE - knife Winrm does not have this issue because it executes [this method](https://github.com/chef/knife-windows/blob/v1.1.0/lib/chef/knife/winrm.rb#L63) which has code near the bottom that [exits appropriately](https://github.com/chef/knife-windows/blob/v1.1.0/lib/chef/knife/winrm.rb#L71-L79).  This is a major problem because the 2 code bases dont share the code to determine if the command failed.  But it does share the common WinRMSession code.  Suggest this gets fixed.

knife bootstrap (ssh) (12.5.1)
* Runs bootstrap via ssh [here](https://github.com/chef/chef/blob/12.0.3/lib/chef/knife/bootstrap.rb#L256)
* Looking at the SSH [method](https://github.com/chef/chef/blob/12.0.3/lib/chef/knife/ssh.rb#L485) it [exits](https://github.com/chef/chef/blob/12.0.3/lib/chef/knife/ssh.rb#L518) appropriately.

So it looks like the change that is needed is to change [this line](https://github.com/chef/knife-windows/blob/v1.1.0/lib/chef/knife/bootstrap_windows_base.rb#L325) to exit the bootstrap_command_result.  That solves the immediate problem.  However it should be noted that the code to execute commands should probably be common within knife-windows to determine success/failure.

**Comment by carpnick** [comment]
FYI - @rschiefer, @danielvanhouten , @gitmlynch  @jimmycliff @mcallb

**Comment by mwrock** [comment]
Thanks @carpnick! I'll have a look.

**Comment by carpnick** [comment]
@mwrock  Thanks.  Will give it a try.

**Comment by mwrock** [comment]
@carpnick its on rubygems now 1.1.1

**Comment by carpnick** [comment]
Tested:
Good bootstrap - Success
Bad bootstrap - Success
Good Winrm Call - Success
Bad Winrm Call - Success

All set.

Will open another issue for an edge condition that has nothing to do with refactor.

**Comment by mwrock** [comment]
good to know. Thanks so much for the feedback!

**Comment by mwrock** [comment]
see https://github.com/WinRb/WinRM/issues/154#issuecomment-152034936

I'm chalking this off to a bug in WinRM

**Comment by carpnick** [comment]
Agreed.  Worth documenting here as a known edge condition of Winrm in the knife winrm  context and in the winrm gem itself I think.  Otherwise folks doing a simple test, or running a simple CLI with no output could be in for a surprise.
