### ISSUE TITLE
NoMethodError: configure_proxy_environment_variables

### ISSUE THREAD

**Issue by puncha** [chef/knife-windows#323]
It seems this [PR](https://github.com/chef/knife-windows/pull/297) breaks bootstrapping a windows node by using Chef-client 12.6.0 and Chef-server 11.1.7:

```
INFO: Using configuration from C:/chef_repo/.chef/knife.rb
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Looking for key winrm_user and found value administrator
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_password and found value XXXXX
DEBUG: Looking for key winrm_port and found value 5985
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Adding 10.41.81.176
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-windows-1.1.1/lib/chef/knife/winrm_session.rb:28:in `initialize': undefined method `configure_proxy_environment_variables' for #<Chef::Application:0x47f8d70> (NoMethodError)
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-windows-1.1.1/lib/chef/knife/winrm_knife_base.rb:198:in `new'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-windows-1.1.1/lib/chef/knife/winrm_knife_base.rb:198:in `create_winrm_session'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-windows-1.1.1/lib/chef/knife/winrm_knife_base.rb:193:in `block in session_from_list'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-windows-1.1.1/lib/chef/knife/winrm_knife_base.rb:190:in `each'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-windows-1.1.1/lib/chef/knife/winrm_knife_base.rb:190:in `session_from_list'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-windows-1.1.1/lib/chef/knife/winrm_knife_base.rb:74:in `configure_session'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-windows-1.1.1/lib/chef/knife/bootstrap_windows_winrm.rb:51:in `run'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/knife.rb:212:in `run'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application/knife.rb:142:in `run'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chef/bin/knife:64:in `load'
        from C:/opscode/chef/bin/knife:64:in `<main>'
```

**Comment by mwrock** [comment]
Yup. The server version doesn't matter. Looks like this commit https://github.com/chef/chef/commit/85d0407a16fa4dfc479d550a96355a6d11f4f551 broke this.

**Comment by samsonkolge** [comment]
Hi,
I am still getting this issue when I try to bootstrap windows "node1" from windows workstation (Windows 8.1) 

$ chef exec knife bootstrap windows winrm -N 192.168.33.93 --winrm-user Administrator --winrm-password 'XXXXX' --bootstrap-no-proxy -VV
INFO: Using configuration from C:/Users/kolge/learn-chef/chef-repo/.chef/knife.rb
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Looking for key winrm_user and found value Administrator
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_password and found value XXXXX
DEBUG: Looking for key winrm_port and found value 5985
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Looking for key ssl_peer_fingerprint and found value
DEBUG: Looking for key ca_trust_file and found value
C:/Users/kolge/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-windows-1.4.1/lib/chef/knife/winrm_knife_base.rb:69:in `resolve_target_nodes': undefined method `split' for nil:NilClass (NoMethodError)
        from C:/Users/kolge/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-windows-1.4.1/lib/chef/knife/winrm_knife_base.rb:62:in `configure_session'
        from C:/Users/kolge/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-windows-1.4.1/lib/chef/knife/bootstrap_windows_winrm.rb:51:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/knife.rb:219:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/application/knife.rb:148:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:61:in `load'
        from C:/opscode/chefdk/bin/knife:61:in `<main>'

Is this fixed? How do I bootstrap a windows node? Please advise.

**Comment by mwrock** [comment]
This is actually a different bug. The bug for this issue results in `NoMethodError: configure_proxy_environment_variables`. The error reported by @samsonkolge is absolutely a bug and I'll open a separate issue to track it. However there is a workaround. The error you are getting is the result of the argument validation occuring too late. So the fact that you are missing the server argument is not producing an actionable error message. You can avoid this by using:
```
chef exec knife bootstrap windows winrm 192.168.33.93 -N 192.168.33.93 --winrm-user Administrator --winrm-password 'XXXXX' --bootstrap-no-proxy -VV
```
Note that the syntax of the bootstrap command is:
```
knife bootstrap windows winrm FQDN (options)
```
You are missing the required FQDN name which can be different (but does not have to be) from the node name passed in with `-N`

**Comment by Taurino3** [comment]
I am using knife version "Chef: 11.12.2" I need the knife-windows to work with this version

The work around does not work, do I need to install a older version of knife-windows?


$knife bootstrap windows winrm <IP> -N <FQDN> -x <USER> -P <PASSWORD> --bootstrap-no-proxy -VV

DEBUG: Looking for key winrm_shell and found value cmd
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value 
DEBUG: Looking for key winrm_user and found value <USER>
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_password and found value <PASSWORD>
DEBUG: Looking for key winrm_port and found value 5985
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value 
DEBUG: Looking for key ssl_peer_fingerprint and found value 
DEBUG: Looking for key winrm_shell and found value cmd
DEBUG: Looking for key winrm_codepage and found value 65001
DEBUG: Looking for key ca_trust_file and found value 
DEBUG: Adding <IP>
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/knife-windows-1.7.0/lib/chef/knife/winrm_session.rb:93:in `configure_proxy': undefined method `configure_proxy_environment_variables' for #<Chef::Application:0x0000000290b580> (NoMethodError)
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/knife-windows-1.7.0/lib/chef/knife/winrm_session.rb:29:in `initialize'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/knife-windows-1.7.0/lib/chef/knife/winrm_knife_base.rb:189:in `new'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/knife-windows-1.7.0/lib/chef/knife/winrm_knife_base.rb:189:in `create_winrm_session'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/knife-windows-1.7.0/lib/chef/knife/winrm_knife_base.rb:184:in `block in session_from_list'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/knife-windows-1.7.0/lib/chef/knife/winrm_knife_base.rb:181:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/knife-windows-1.7.0/lib/chef/knife/winrm_knife_base.rb:181:in `session_from_list'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/knife-windows-1.7.0/lib/chef/knife/winrm_knife_base.rb:63:in `configure_session'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/knife-windows-1.7.0/lib/chef/knife/bootstrap_windows_winrm.rb:58:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife.rb:492:in `run_with_pretty_exceptions'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife.rb:174:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/application/knife.rb:135:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/bin/knife:25:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/bin/knife:23:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/bin/knife:23:in `<main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `<main>'
