### ISSUE TITLE
Need to skip downloading Chef Client

### ISSUE THREAD

**Issue by sully255** [chef/knife-windows#324]
I have machines that are behind a firewall and dont have access to the internet.  When trying to bootstrap a windows machine the bootstrap fails because it cant connect to the internet to download the latest client.   I have installed the client locally and I am wondering what I can add to the knife.rb file to skip the downloading of the client.

**Comment by mwrock** [comment]
You can use a `--bootstrap-install-command` command and basically use a command that does nothing like `--bootstrap-install-command 'exit 0'`. Give that a try.

**Comment by btm** [comment]
You can also pass `--msi-url` to specify where to download and install the MSI from locally, in case that's easier than how you're currently installing.

I'll add to @mwrock's suggestion that there is some stuff that happens as part of the install like placing the client keys, creating the configuration file, running chef-client. If you still want that to happen you could try something like `--bootstrap-install-command "echo skipping client installation"`

**Comment by btm** [comment]
In core Chef we check if the client is already installed, we should do that here too in ` bootstrap/windows-chef-client-msi.erb`.

https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb#L169

**Comment by bhaliti** [comment]
I was facing the same issue. bootstrapping windows servers behind a firewall. no egress. so I installed chef-client*.msi and setup the /etc/chef - client.rb etc. trusted_sites etc.
and then modified the knife.rb file and included this:
knife[:bootstrap_install_command] = "--bootstrap-install-command"

basically like they said above skip trying to install it since it's already installed.

**Comment by vinayak-thbs** [comment]
You can directly run the chef client passing the runlist and if it fails you bootstrap it. Below snippet solved my case.

knife winrm "$nodeName" "chef-client -r $runList" -m -x <username> -P "password"
if [ $? != 0 ]; then
	echo "CHEF INSTALLATION NOT FOUND HENCE BOOTSTRAPING"
	echo "Bootstrapping $nodeOs node"
	knife bootstrap windows winrm $ipAddress --winrm-user <username> -P 'password' -N $nodeName  --node-ssl-verify-mode none -y --bootstrap-version $CLIENT_VERSION -r "$runList"
fi.

I used the above to run in my jenkins execute shell
