### ISSUE TITLE
Documentation proposal - add information how install the plugin

### ISSUE THREAD

**Issue by it-praktyk** [chef/knife-windows#328]
My suggestion is as follows: add a paragraph in the section "Requirements / setup" describing the procedure for installing the plugin similar to that described in the article https://docs.chef.io/plugin_knife_custom.html.

If you agree I'll prepare an update and a pull request.

**Comment by mwrock** [comment]
you thinking along the lines of https://github.com/chef/winrm-s#installation ?

That would be great.

**Comment by it-praktyk** [comment]
Yes, something like this, but also "if you would like store plugin in  in the cookbook repository you need copy files like or use script xyz.ps/rb"

**Comment by mwrock** [comment]
I think for plugins that are available on rubygems like this one, its best to just install from ruby gems. Installing them to the plugin directory is really intended for small, custom plugins and not knife-windows.

**Comment by it-praktyk** [comment]
Yes, I agree and installing from ruby gems should be described as a prefered installation method. Other can be mentioned also with redirection to the Chef documentation. I'll try prepare update tomorrow.

**Comment by it-praktyk** [comment]
Today I tested knife-windows installation process - I've used clean vagrant box bento/fedora22 https://atlas.hashicorp.com/bento/boxes/fedora-22 with vmware_workstation provider.

The list of used commands to finalize knife-windows

```
dnf update -y                                                                
dnf clean all
reboot                                                                
wget https://opscode-omnibus-packages.s3.amazonaws.com/el/7/x86_64/chef-12.6.0-1.el7.x86_64.rpm                                                               
rpm -i ./chef-12.6.0-1.el7.x86_64.rpm                                         
cd /opt/chef/embedded/bin/                                                    
./gem install knife-windows 2>&1 | tee /vagrant/commands2.txt                 
dnf install gcc -y 2>&1 | tee --append /vagrant/commands2.txt                 
./gem install knife-windows 2>&1 | tee --append /vagrant/commands2.txt        
dnf install patch -y 2>&1 | tee --append /vagrant/commands2.txt               
./gem install knife-windows 2>&1 | tee --append /vagrant/commands2.txt        
dnf install libxslt -y 2>&1 | tee --append /vagrant/commands2.txt             
./gem install knife-windows 2>&1 | tee --append /vagrant/commands2.txt        
dnf install zlib-devel -y 2>&1 | tee --append /vagrant/commands2.txt         
./gem install knife-windows 2>&1 | tee --append /vagrant/commands2.txt  
```

The attached file commands2.txt is compilation of commands outputs and commands from history.
[commands2.txt](https://github.com/chef/knife-windows/files/79195/commands2.txt)

**Comment by cheeseplus** [comment]
We encourage this plugin to be consumed as part of ChefDK and not as a standalone gem nor do we recommend it being consumed via cookbook - at least that's very advanced usage and we don't want to encourage that pattern.
