### ISSUE TITLE
NoMethodError: undefined method `debug' for nil:NilClass in WINRM

### ISSUE THREAD

**Issue by wv-cfromm** [chef/knife-windows#331]
NoMethodError: undefined method `debug' for nil:NilClass in winrm.  Knife version 1.1.3

Error is caused by logger.debug lines in winrm_service.rb.  Commenting these lines allowed knife-windows to work.

Chris

**Comment by mwrock** [comment]
what version of winrm do you have?

**Comment by wv-cfromm** [comment]
OS: 6.3.9600 SP: 0.0 Stack: 3.0
However, it really just looks as winrm_service.rb doesn't think logger is instantiated.

**Comment by mwrock** [comment]
my apologies. I meant the winrm gem. This is actually a bug in that gem and not knife_windows.

**Comment by wv-cfromm** [comment]
Looks like 1.5.0

**Comment by mwrock** [comment]
actually this looks to be a bug in monkey patching winrm-s moving there. see https://github.com/chef/winrm-s/issues/32
