### ISSUE TITLE
Can't boostrap Windows node

### ISSUE THREAD

**Issue by mlckha** [chef/knife-windows#338]
Hi,

I need your help to bootstrap windows node via 5985 port.

My winrm configuration on my windows node:
![w](https://cloud.githubusercontent.com/assets/4509437/12576860/f510932c-c416-11e5-9001-25bb3254b339.png)

When i try to boostrap him from my chef workstation i get this error (can't find help about it):

![sans titre](https://cloud.githubusercontent.com/assets/4509437/12576918/708cffcc-c417-11e5-8a09-b2bead10efa5.png)

Thank's a lot for your help,
Have a nice day,
Mlckha

**Comment by mwrock** [comment]
It looks as though the response received from the winrm port is not a winrm based SOAP response but some kind of HTML. This often indicates that there is a proxy in between you and the node intercepting the requests. Does that sound right for your environment? If so, you can configure knife-windows to honor your proxy settings by placing them in your `knife.rb` as described in the `proxy settings` section of this [doc](https://docs.chef.io/config_rb_knife.html)

**Comment by mlckha** [comment]
Thank's for the fast reply. I add my proxy in my knife.rb but i have always the same error

![p](https://cloud.githubusercontent.com/assets/4509437/12577684/46964e44-c41c-11e5-9376-a17493d87845.png)

**Comment by mwrock** [comment]
`knife[:bootstrap_proxy]` would impact any proxy between the node and the chef server and may indeed be necessary. However for traffic to pass through a proxy between the workstation and the node which is the case here, use `knife[:http_proxy]`.

**Comment by mlckha** [comment]
Yes i have try this 2 options in knife.rb but doesn't work :(

**Comment by mwrock** [comment]
one other thing to try is settng the `HTTP_PROXY`environment variable to that value before bootstrapping. If that fails, it would be helpful to observe a http stream trace if possible.

**Comment by mlckha** [comment]
That works thank's :)
