### ISSUE TITLE
WinRM::WinRMAuthorizationError: Boostrap Windows

### ISSUE THREAD

**Issue by mlckha** [chef/knife-windows#339]
Hi,

I need your help again :) I can't boostrap my windows node from my chef workstation :

![test](https://cloud.githubusercontent.com/assets/4509437/12583171/ad3024c0-c441-11e5-969d-32e649dbad06.png)

That strange because i can Winrm this windows node via my local computer windows with the same username/password and hostname

Thank's,
Have a nice day,
Mlckha

**Comment by mwrock** [comment]
would I be correct to assume the workstation is not a windows machine? If so, knife-windows 1.1.x cannot use the same auth protocol on linux/mac and it instead uses basic auth which requires some special config on the node. knife-windows 1.2 released just yesterday addresses this. Your best option is to `gem install` that.

**Comment by mlckha** [comment]
Hi,
Indeed, my workstration in a RHEL 7.
I have updated the knife-windows tools in 1.2 but i have always the same authenticate error.

Below, my Winrm configuration on my windows 2008R2 node:
![sans titre](https://cloud.githubusercontent.com/assets/4509437/12608548/0023378a-c4dd-11e5-9cf8-697c7d7ff1ee.png)

Than'ks for your help :)
Have a nice day,
Florent

**Comment by mwrock** [comment]
here is another thing to try. It could be that knife-windows 1.2.0 is not actually running above. Try running `chef gem install knife-windows` prefixing with `chef` is the and that may ensure that the gem is installed in the correct place. Then give this another shot.

**Comment by mlckha** [comment]
I have a new error due to the upgrade :
![aa](https://cloud.githubusercontent.com/assets/4509437/12638501/e56d0206-c59d-11e5-90a6-c9d5812121a6.png)

**Comment by mwrock** [comment]
Hmm. I'm guessing this is another issue with your proxy. Its making the initial winrm and trying to initiate the authentication handshake but the HTTP headers are missing auth headers. Are you setting the `HTTP_PROXY` environment variable with your proxy info?

**Comment by mlckha** [comment]
Yes indeed, i have kick this proxy of my configuration ! :)

**Comment by mwrock** [comment]
ok. its possible that negotiate as implemented here has problems with proxy. will need to investigate that further. In the meantime you could try basic auth or SSL.

**Comment by mlckha** [comment]
I try to bootstrap with local account, i have this error:
![sans titre](https://cloud.githubusercontent.com/assets/4509437/12649552/5935fc4c-c5df-11e5-80f5-300b7fbb73ba.png)
Maybe i can't use winrm on 5985 ?

Thank's a lot for help me :+1: 
Have a nice day :)

**Comment by mwrock** [comment]
Ah. Validatorless bootstrap is not permitted with basic auth. You will need to do this via SSL.

**Comment by mlckha** [comment]
Where i can permit this auth ? via Chef-server ou chef workstation in knife.rb ?

**Comment by mwrock** [comment]
A couple things here:

1. I did validate (at least in my environment) that negotiate auth from a linux workstation is successful when routing through a proxy. So either there is a specific proxy setting or something entirely different at play here.
2. For validator bootstrapping, you can download the validator .pem file from your chef server and then provide the path to that file in your knife.rb
```
validation_client_name   "ment-validator"
validation_key           "#{current_dir}/ment-validator.pem"
```

**Comment by btm** [comment]
If you need further help, please post a message in the 'chef' category on [Discourse ](https://discourse.chef.io/ )instead of filing an issue here.

https://discourse.chef.io/

**Comment by cbrit** [comment]
@mlckha did you ever find a solution to this? Sorry to dig up an old thread but I've got a team that has been stuck with this exact issue for a couple of weeks. For them it occurs with a Jenkins.
