### ISSUE TITLE
Bootstrap winrm fails executing chef client on Win 2012r2 from Mac OSX

### ISSUE THREAD

**Issue by hanselmahlaola** [chef/knife-windows#357]
This issue is similar to https://tickets.opscode.com/browse/KNIFE-410 

Bellow is the error out put, Please assist

knife bootstrap windows winrm 192.168.8.2 --winrm-user admin --winrm-password 'P@55w0rd' --node-name win-goci1 --run-list 'role[install-go]'
Creating new client for win-goci1
Creating new node for win-goci1

Waiting for remote response before bootstrap.192.168.8.2 . 
192.168.8.2 Response received.
Remote node responded after 0.02 minutes.
Bootstrapping Chef on 192.168.8.2
192.168.8.2 Rendering "C:\Users\admin\AppData\Local\Temp\bootstrap-18837-1460029501.bat" chunk 1 
192.168.8.2 'echo.' is not recognized as an internal or external command,
192.168.8.2 operable program or batch file.
ERROR: Failed to execute command on 192.168.8.2 return code 1

**Comment by mwrock** [comment]
can you report the output with debug logging adding `-VV` to the command? Also try this:
```
knife winrm -m 192.168.8.2 echo. --winrm-user admin --winrm-password 'P@55w0rd'
```
That just runs `echo.` via winrm and nothing else. You might also see if you can run `echo.` from a command window on the node.

If it can't understand `echo.` there is likely an issue on the node.

**Comment by btm** [comment]
If you need further help, please post a message in the 'chef' category on [Discourse](https://discourse.chef.io/) instead of filing an issue here.

https://discourse.chef.io/
