### ISSUE TITLE
Problem with bootstrapping Windows using WinRM

### ISSUE THREAD

**Issue by kdugardyn66** [chef/knife-windows#361]
Hi,

I'm trying to get my Windows Server bootstrapped but getting continuously following error:
Connecting to windows
DEBUG: Looking for bootstrap template in /opt/chef/embedded/apps/chef/lib/chef/knife/bootstrap/templates
DEBUG: Found bootstrap template in /opt/chef/embedded/apps/chef/lib/chef/knife/bootstrap/templates
DEBUG: Adding windows
DEBUG: establishing connection to windows:22
ERROR: Network Error: getaddrinfo: Name or service not known
Check your knife configuration and network settings

My command I'm running is: knife bootstrap windows winrm IP_ADDRESS -N FDDN -x 'domain\username' -P password -VV

I've installed knife-windows.0.8.5  (which is working well in the past).

Kind Regards,
Kris

**Comment by mwrock** [comment]
What happens using a modern version like 1.4.0?

**Comment by WeekendsBull** [comment]
I have installed ChefDK (v0.12.0) and then run "chef exec knife bootstrap windows winrm ...." (we are on OHC and learned from Zack). However, the same command doesn't work any more ...

**Comment by mwrock** [comment]
Are you getting the same `getaddrinfo` error mentioned above?

**Comment by WeekendsBull** [comment]
Hi Matt, yes unfortunately, I got the same error on the getaddrinfo error as below. 

C:/opscode/chef/embedded/lib/ruby/2.1.0/socket.rb:232:in `getaddrinfo' 
: 
getaddrinfo: No such host is known. (SocketError)

**Comment by mwrock** [comment]
Just taking another look at this issue and noticing @kdugardyn66 output indicates that knife-windows is not loaded.Its trying to contact a hostname windows on port 22. So its using the core knife bootstrap using ssh.

**Comment by Bluebeam** [comment]
@mwrock I don't think  I need to run Chef exec anymore to bootstrap a windows instance in AWS. It works how it used to work, "knife bootstrap windows winrm...."

**Comment by cheeseplus** [comment]
Closing old issues that were resolved or a result of configuration error as this one.
