### ISSUE TITLE
OutOfMemory when issuing commands in Powershell using knife winrm

### ISSUE THREAD

**Issue by chef09210** [chef/knife-windows#365]
Receive an OutOfMemory exception when executing simple powershell commands using a knife winrm session to initiate a chef-client run with a recipe containing the command.

knife winrm "10.100.1.2" "chef-client -o 'recipe[test]'" -x 'Administrator' -P 'Password1'

Chef-client and recipe/command works when running the command locally.

Debug log:

[report.txt](https://github.com/chef/knife-windows/files/239615/report.txt)

Winrm configuration

```
Config
    MaxEnvelopeSizekb = 500
    MaxTimeoutms = 300000
    MaxBatchItems = 32000
    MaxProviderRequests = 4294967295
    Client
        NetworkDelayms = 5000
        URLPrefix = wsman
        AllowUnencrypted = false
        Auth
            Basic = true
            Digest = true
            Kerberos = true
            Negotiate = true
            Certificate = true
            CredSSP = false
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        TrustedHosts
    Service
        RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)(A;;GR;;;IU)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;WD)
        MaxConcurrentOperations = 4294967295
        MaxConcurrentOperationsPerUser = 1500
        EnumerationTimeoutms = 240000
        MaxConnections = 300
        MaxPacketRetrievalTimeSeconds = 120
        AllowUnencrypted = false
        Auth
            Basic = false
            Kerberos = true
            Negotiate = true
            Certificate = false
            CredSSP = false
            CbtHardeningLevel = Relaxed
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        IPv4Filter = *
        IPv6Filter = *
        EnableCompatibilityHttpListener = false
        EnableCompatibilityHttpsListener = false
        CertificateThumbprint
        AllowRemoteAccess = true
    Winrs
        AllowRemoteShellAccess = true
        IdleTimeout = 7200000
        MaxConcurrentUsers = 10
        MaxShellRunTime = 2147483647
        MaxProcessesPerShell = 25
        MaxMemoryPerShellMB = 2048
        MaxShellsPerUser = 30
```

Timeout and memorypershellmb parameters are fine, system has 32GB of RAM

**Comment by mwrock** [comment]
What version of powershell is your node running? If it is v3, its possible you are hitting a bug introduced by an update to that version which will ignore `MaxMemoryPerShellMB`. See https://support.microsoft.com/en-us/kb/2842230.

The remedy is to install a hotfix or upgrade to a later version of powershell.

If you are not affected by this bug, 2GB should certainly be more than enough. You might check if something else is hogging memory but I'd think 32GB would be ample for most workloads.

**Comment by chef09210** [comment]
The installed hotfix seems to have fixed the issue, thanks.
