### ISSUE TITLE
knife bootstrap for Windows without doing winrm config

### ISSUE THREAD

**Issue by indrakkk** [chef/knife-windows#370]
HI all,

       I have been bootstrapped a node(i.e windows image) from my workstation.But before doing bootsrap i need to do winrm quick configuration steps for 5985/5986 port access and other authentication.
       So my qusetion is ,whether we can do bootstrap in windows without doing any manual configuration like we do bootstrap for linux nodes? If it is possible means we can done this with azure or aws platform.

Thanks in advance

**Comment by mwrock** [comment]
The answer to this question really depends on Windows os and desired winrm configuration. So the answer is "yes you can bootstrap without any manual configuration" if you are using a Windows 2012 R2 image and intend to use an HTTP endpoint. 2012R2 has winrm enabled by default with a http listener. Older os versions or client based versions (like windows 7, 8.1, 10) need to have winrm enabled. And if you want to connect via HTTPS, you need to add an https listener.

**Comment by btm** [comment]
If you need further help, please post a message in the 'chef' category on [Discourse ](https://discourse.chef.io/) instead of filing an issue here.

https://discourse.chef.io/
