### ISSUE TITLE
knife-windows config options need an overhaul

### ISSUE THREAD

**Issue by curiositycasualty** [chef/knife-windows#371]
Now finding myself in need of knife-windows, I'm noticing that many of the knife config options as resolved by this plugin expect `Chef::Config[:knife]` which no longer exists. This can be worked around by doing the below in your `knife.rb` but as noted by @hh in #290, this differs from the pattern established by the `ssh_*` options and conflicts with `knife node show`'s `--attribute`.

```
knife.tap do |k|
  k.winrm_user 'bob'
  k.winrm_password 'super_secret'
  k.attribute 'ipaddress'
end
```

related: #290

**Comment by mwrock** [comment]
I'm a bit confused by:

> many of the knife config options as resolved by this plugin expect Chef::Config[:knife] which no longer exists

`Chef::Config[:knife]` is still referenced heavily in core chef and you can find the same resolution in knife ssh and knife bootstrap. Can you provide more details around "the pattern established by the ssh_* options" that you expect this plugin to follow?

Regarding `--attribute`, this plugin really just attempts to mirror `knife ssh`'s [use of `--attribute`](https://github.com/chef/chef/blob/master/lib/chef/knife/ssh.rb#L50). I would agree that the conflict with `knife node` is unfortunate but the cure for that is likely not in this gem.

**Comment by curiositycasualty** [comment]
Sorry, you're right. `Chef::Config[:knife]` is still around. I was confused because it doesn't respond with a Hash object.
```
[5] pry(#<Chef::Knife::Winrm>)> Chef::Config[:knife].is_a?Hash
false
[6] pry(#<Chef::Knife::Winrm>)> Chef::Config[:knife].is_a?Class
true
[7] pry(#<Chef::Knife::Winrm>)> whereami

/Users/trill/.gem/ruby/2.1.8/gems/knife-windows-1.4.1/lib/chef/knife/knife_windows_base.rb @ line 27 Chef::Knife::KnifeWindowsBase#locate_config_value:

    23: def locate_config_value(key)
    24:   key = key.to_sym
    25:   value = config[key] || Chef::Config[:knife][key] || default_config[key]
    26:   Chef::Log.debug("Looking for key #{key} and found value #{value}")
 => 27:   require 'pry'; binding.pry
    28:   value
    29: end
```

The pattern established by `knife ssh ...` is how the ssh_* related Chef::Config items are name-spaced accordingly ("ssh_attribute", "ssh_user", "ssh_password", "ssh_identity_file", etc.).

I think you may have linked to the one, singular line at which the node attribute to be used for the ssh connection is reference to solely as `:attribute`.

It's worth noting that the line you linked to is also accompanied by: https://github.com/chef/chef/blob/master/lib/chef/knife/ssh.rb#L183-L206 which is significantly more robust than `knife-windows` mechanism generic for accomplishing the same task, `Chef::Knife::KnifeWindowsBase#locate_config_value` @ https://github.com/chef/knife-windows/blob/master/lib/chef/knife/knife_windows_base.rb#L23-L28

**Comment by mwrock** [comment]
ok I see. I was just looking at the cli param name and not the knife config name. You are totally right and this should be changed here.

**Comment by btm** [comment]
We should change these when we move bootstrap from knife-windows into core.
