### ISSUE TITLE
knife bootstrap silent fail on windows 2008 x86

### ISSUE THREAD

**Issue by lihlcnkr** [chef/knife-windows#373]
Hi,

I use knife bootstrap on windows 2008 x86 server(installed korean language pack) is silent fail.
It created windows batch file, but the batch file not executed and return code is 0.

knife bootstrap debug log is like this.

> 10.30.44.109 Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24187-1466852983.bat" > chunk 7 
> DEBUG: 10.30.44.109=>:command_cleanup[cmd.exe /C echo Rendering "%TEMP%\bootstrap-24187-1466852983.bat" chunk 7 && >> "%TEMP%\bootstrap-24187-1466852983.bat" (echo.SET "PATH=%PATH%;C:\ruby\bin;C:\opscode\chef\bin;C:\opscode\chef\embedded\bin") && >> "%TEMP%\bootstrap-24187-1466852983.bat" (echo.chef-client -c c:/chef/client.rb -j c:/chef/first-boot.json) && >> "%TEMP%\bootstrap-24187-1466852983.bat" (echo.)]
> DEBUG: 10.30.44.109=> :shell_close
> DEBUG: cmd.exe /C "%TEMP%\bootstrap-24187-1466852983.bat"
> DEBUG: 10.30.44.109 => :run_command[cmd.exe /C "%TEMP%\bootstrap-24187-1466852983.bat"]
> DEBUG: 10.30.44.109 => :command_cleanup[cmd.exe /C "%TEMP%\bootstrap-24187-1466852983.bat"]
> DEBUG: 10.30.44.109 => :shell_close

the version info is 

> knife-windows version:1.4.1
> winrm version:1.8.1

and after digging, I think found that.  on source code lib/chef/knife/winrm_session.rb "relay_command" method
` remote_id = @winrm_session.open_shell`
`        command_id = @winrm_session.run_command(remote_id, command)` 
=> it's not run batch file. just exit code is 0, and run other command is OK

I thinks it's related this issue
[[WinRb/WinRM#181]](https://github.com/WinRb/WinRM/issues/181)

and when I changed /lib/chef/knife/winrm_session.rb => relay_command() method
`remote_id = @winrm_session.open_shell(codepage: 949)`
It will run batch script successfully. 
=> but looks like this is bad idea for always need setting codepage. not using utf-8.

sound like the it is winrm_session run_command bug. but I'm not sure.
how to fix this? 

thx

**Comment by lihlcnkr** [comment]
I thinks it's related this issue
https://github.com/WinRb/WinRM/issues/181

**Comment by mwrock** [comment]
It sounds like the proper fix is to allow knife-windows to take a codepage flag and pass that to winrm. WinRM v2 is on the verge of release and we will be rewiring knife-windows to use that and will keep this in mind when we do.

**Comment by lihlcnkr** [comment]
thx very much @mwrock ~
how about check windows version, and use "chcp" command to  get current console code page, and use this codepage to open shell?
just like this Pseudocode.
`winrm = WinRM::WinRMWebService.new(endpoint, :kerberos, :realm => krb5_realm)
winrm.create_executor do |executor|
  executor.run_cmd('chcp') do |stdout, stderr|
     pagecode = stdout.replace(/.*(\d*).*/,"$1")​​​​​​​​​​​​​​​​​​​​​​​​​​​;
  end
end
remote_id = @winrm_session.open_shell(codepage: pagecode)
run_command(remote_id, command)
`
http://ss64.com/nt/chcp.html

**Comment by mwrock** [comment]
Yeah that might work as long as `chcp` can come back since we will be using codepage `437` to call `chcp`.

**Comment by mwrock** [comment]
fixed via #389
