### ISSUE TITLE
Display version of knife-windows in standard command output

### ISSUE THREAD

**Issue by vinyar** [chef/knife-windows#374]
# Why?

Having knife-windows casually display its own version would immensely simplify troubleshooting.
# Use case:

Right now, when we (support team) get error output, casual users are generally very good at including the whole output (even if it's a screenshot). However, pulling out the version of knife-windows in use is often a complex task, especially when there is chef-client and chefdk and multiple version of knife-windows installed on the workstation.
# Example:

Similar to how chef-client displays its own version on every run.

Thank you

**Comment by mwrock** [comment]
:+1: Yeah. This would be good.

**Comment by btm** [comment]
Windows bootstrap support is now in core as of Chef Infra 15, so any issues will be attributable to the version of Chef Infra being used. I think this alleviates the need for this feature now.

The plan right now is that going forward knife-windows is only expected to contain the `knife winrm` and `knife wsman test` commands.
