### ISSUE TITLE
Kerberos_service

### ISSUE THREAD

**Issue by kev111** [chef/knife-windows#375]
What is this value? The kdc? Is there a working example of kerberos with active directory?

**Comment by mwrock** [comment]
The `kerberos_service` specifies the service class name of a kerberos SPN. The default is `HTTP`. The winrm gem uses this to build a kerberos SPN like so:
```
"#{service}/#{@endpoint.host}@#{realm}"
```

Other common values may be: `rpc`, `imap`, `mssql` to name a few.

**Comment by btm** [comment]
If you need further help, please post a message in the 'chef' category on [Discourse ](https://discourse.chef.io/ )instead of filing an issue here.

https://discourse.chef.io/
