### ISSUE TITLE
Working with Chef Behind Your Firewall

### ISSUE THREAD

**Issue by bhaliti** [chef/knife-windows#379]
Hi,

I could really use some help with this. My environment does not allow outbound access, so I would like to place the chef-client on windows systems on the template. Where do i place it, do I install it??
is there anything that I need to do with it, create client.rb file etc. do I then need to change any files on workstation side??? 

:convergence_options => {
          :install_msi_url=>"https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-windows-11.16.4-1.windows.msi", 
          :install_sh_url=>"/tmp/chef-install.sh -v 11.16.4"

this is what I am talking about, how do I change this from using egress to point it to local (template) 
is there a specific directory where the client must be installed etc. 

Please be as specific as possible I am new to chef.

thanks

**Comment by mwrock** [comment]
I'd have a look at [unattended installs](https://docs.chef.io/install_bootstrap.html#unattended-installs). You could install the chef client on your vm template along with its validator pem and client.rb settings. When it converges the first time, it should essentially bootstrap itself and not need to go out to the internet to download the client.

I'm closing here but please ask on the dev user group at https://discourse.chef.io/ if you have more questions.

**Comment by martinmosegaard** [comment]
Take a look at this: https://github.com/chef/knife-windows/issues/324
You should have at least two options:

1. Copy the MSI to your node template, then call knife with something like `--bootstrap-install-command "msiexec /i C:\temp\chef-client-xx.msi"
2. Place the MSI on a server in your environment (like Artifactory or your Chef Server), then call knife with the `--msi-url` option.
