### ISSUE TITLE
Something error during my 'knife bootstrap windows ssh'

### ISSUE THREAD

**Issue by QiaoZijian** [chef/knife-windows#383]
I installed the latest `knife-windows 1.5.0` on my chef-server `Chef: 11.14.2 ` and updated `bootstrap_windows_base.rb` file into the newest fixed version according to #380.
But I got the error messages below when I invoke the command` knife bootstrap windows ssh windowsclient.xxx -p 20022 -x Administrator -P MYPASSWORD`. I am really wondered why there is a syntax error... , can anyone help me?~
```
Bootstrapping Chef on windowsclient.xxx
windowsclient.xxx /bin/sh: -c: line 0: syntax error near unexpected token `('
windowsclient.xxx /bin/sh: -c: line 0: `cmd.exe /C echo Rendering %TEMP%bootstrap-5909-1471505161.bat chunk 1 && >> %TEMP%bootstrap-5909-1471505161.bat (echo.@rem) && >> %TEMP%bootstrap-5909-1471505161.bat (echo.@rem Author:: Seth Chisamore ^(^<schisamo@chef.io^>^)) &&'
windowsclient.xxx sh: -c: line 0: unexpected EOF while looking for matching `"'
windowsclient.xxx sh: -c: line 1: syntax error: unexpected end of file
windowsclient.xxx /bin/sh: -c: line 0: syntax error near unexpected token `('
windowsclient.xxx /bin/sh: -c: line 0: `cmd.exe /C echo Rendering %TEMP%bootstrap-5909-1471505161.bat chunk 3 && >> %TEMP%bootstrap-5909-1471505161.bat (echo.echo.}) && >> %TEMP%bootstrap-5909-1471505161.bat (echo.echo.) && >> %TEMP%bootstrap-5909-1471505161.bat (ec'
windowsclient.xxx sh: -c: line 0: unexpected EOF while looking for matching `"'
windowsclient.xxx sh: -c: line 1: syntax error: unexpected end of file
windowsclient.xxx sh: 2) && >> %TEMP%bootstrap-5909-1471505161.bat : command not found
windowsclient.xxx sh: -c: line 0: unexpected EOF while looking for matching `"'
windowsclient.xxx sh: -c: line 1: syntax error: unexpected end of file
windowsclient.xxx /bin/sh: -c: line 0: syntax error near unexpected token `('
windowsclient.xxx /bin/sh: -c: line 0: `cmd.exe /C echo Rendering %TEMP%bootstrap-5909-1471505161.bat chunk 7 && >> %TEMP%bootstrap-5909-1471505161.bat (echo.echo.log_level        :info) && >> %TEMP%bootstrap-5909-1471505161.bat (echo.echo.log_location     STDOUT) && >'
windowsclient.xxx '%TEMP%bootstrap-5909-1471505161.bat' is not recognized as an internal or external command,
windowsclient.xxx operable program or batch file.
```
In addition, my windows chef-client `Chef Client v12.7.2` is installed on Windows Server 2016 TP5, and the sshd I used is [OpenSSH for Windows](http://www.mls-software.com/opensshd.html). Hope for anyone's suggestion.~

**Comment by mwrock** [comment]
We have not released this fix yet to rubygems @QiaoZijian. If you are comfortable cloning master and trying via bundler, that should work. Otherwise wait for the next release (likely 1.5.1) due out soon.

**Comment by QiaoZijian** [comment]
@mwrock Thank you so much !~ And I have tried to walk around with `windows winrm`. It's cool that I can easily bootstrap the node on `Windows Server 2016 TP5`. : )
But I can't bootstrap the node running as a windows container on my `Windows Server 2016 TP5`. I can run `knife wsman test windowsclient.xxx -m -p 25985` with the result `Connected successfully to windowsclient.xxx at http://windowsclient.xxx:25985/wsman`. But when I ran `knife bootstrap windows winrm`, I got the error messages:
```
Waiting for remote response before bootstrap.......................ERROR: No response received from remote node after 1.85 minutes, giving up.
ERROR: Exception: [WSMAN ERROR CODE: 2147942405]: <f:WSManFault Code='2147942405' Machine='windowsclient.xxx' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='%systemroot%\system32\winrscmd.dll' provider='Shell cmd plugin'>Access is denied. </f:ProviderFault></f:Message></f:WSManFault>
ERROR: WinRM::WinRMWSManFault: [WSMAN ERROR CODE: 2147942405]: <f:WSManFault Code='2147942405' Machine='windowsclient.xxx' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='%systemroot%\system32\winrscmd.dll' provider='Shell cmd plugin'>Access is denied. </f:ProviderFault></f:Message></f:WSManFault>
```
At first, I thought maybe it's something wrong with `WSMAN ERROR 'Shell cmd plugin' Access is denied`. But next, I ran the cmd `knife bootstrap windows winrm ...` with a wrong port `-p WrongPort`, I got the same error messages. I am new to WinRM, so I wonder whether just expose port 5985 is enough for this service? Or is it really caused by `ERROR: Exception: [WSMAN ERROR CODE: 2147942405]`?
I'm so sorry to trouble you again, but I really don't know how to solve it...
PS, I have learnt a lot from your [blog ](http://www.hurryupandwait.io/). It's really COOL!~ Thank you once again~~~
