### ISSUE TITLE
Problem with node-ssl-verify-mode none 

### ISSUE THREAD

**Issue by noresjo** [chef/knife-windows#386]
I want to ignore ssl verification on my node. From my workstation I use `knife windows bootstrap winrm --node-ssl-verify-mode none` . I expect` client.rb` on the target to contain `ssl_verify_mode :verify_none`. It does not. If I add it to `client.rb` on the node manually after the bootstrap, things work much better.

Am I missing something? `windows_bootstrap_context.rb` sees to have code to handle the above but for me it's not working

**Comment by noresjo** [comment]
`--server-url` works fine though.

**Comment by mwrock** [comment]
I have confirmed this is a bug and have submitted #388 to fix.
