### ISSUE TITLE
Any plans to add elevated shell to bootstrap command

### ISSUE THREAD

**Issue by jugatsu** [chef/knife-windows#415]
Are there any plans to add elevated shell to _knife bootstrap windows winrm_ commad? It would be super useful.

> ak@ak-pc:~$ knife bootstrap windows winrm -m 192.168.55.10 -x vagrant --winrm-shell elevated
WARNING: No knife configuration file found
WARNING: The cmd shell is the only valid winrm-shell for 'knife bootstrap windows winrm'. Switching to the cmd shell.

**Comment by mwrock** [comment]
Not in the immediate future. The challenge is that a lot of the code involved in bootstrap must work for both winrm and ssh.  The powershell and elevated shells cannot currently be used over an ssh transport. That may change as Microsoft's SSH support progresses but right now bootstraop needs to remain `cmd`.

**Comment by jugatsu** [comment]
OK.
