### ISSUE TITLE
knife winrm not working

### ISSUE THREAD

**Issue by huamichaelchen** [chef/knife-windows#428]
Hi, 
Recently I'm trying to run knife winrm command to do some chef deployment through bamboo. 
However, I'm getting this error all of sudden. 

Here are some version info that could be helpful :) 

- chef 12.12.15
- chefdk 0.3.6
- knife-windows-0.8.6
- winrm-1.3.6
- winrm-s-0.3.6

`FATAL: Cannot find subcommand for: 'winrm role:victoria AND chef_environment:dev13 del /Q C:\chef\cache\*.zip & del /Q C:\chef\cache\*.md5 & del /Q C:\chef\cache\*.msi & del /Q C:\chef\cache\*.exe & del /Q C:\chef\cache\*.gz & del /Q C:\chef\cache\*.conf -x SOMEUSER -P SOMEPASSWORD -t ssl -p 5986 -f C:\work\SOME.pem --config C:\work\.chef\knife-12.rb'
FATAL: Cannot find subcommand for: 'winrm role:SOMEROLE AND chef_environment:dev13 chef-client -x SOMEUSER -P SOMEPASSWORD -t ssl -p 5986 -f C:\work\SOME.pem --config C:\work\.chef\knife-12.rb'`

**Comment by cheeseplus** [comment]
This appears to be an env issue, not really one with the knife-windows code. If this condition still exists please open a new issue with current versions of the software.
