### ISSUE TITLE
Remove the deprecated identity_file option

### ISSUE THREAD

**Issue by tas50** [chef/knife-windows#469]
This option has been deprecated for many years and was replaced with ssh_identity_file. Make sure we're using ssh_identity_file everywhere in knife-windows instead of identify_file.

**Comment by dheerajd-msys** [comment]
As we agreed upon to keep `--identity-file` option until `chef v14` goes EOL. Other deprecated options are removed in the PR [chef/knife-windows#470](https://github.com/chef/knife-windows/pull/470)
