### ISSUE TITLE
Remove support for Chef 12 and Chef 12 specs

### ISSUE THREAD

**Issue by tas50** [chef/knife-windows#474]
We have some leftover Chef 12 support in this knife plugin that can go away at this point. This file in particular has support for Chef 12 https://github.com/chef/knife-windows/blob/master/spec/spec_helper.rb#L83

This should all get cleaned up since we already require Ruby 2.4 which means Chef 13+

**Comment by dheerajd-msys** [comment]
@tas50, @lamont-granquist Could you take a look on this PR?
