### ISSUE TITLE
knife-windows fixates on chef-15

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/knife-windows#485]
Knife-windows 3.0.3 is hard-fixed to demand chef-15 .  Does it require a feature only in chef-15, or can this be relaxed to allow chef-14?

We like to stay up-to-date, but the JDK-like license on Chef-15 means that like others in our sector we can probably never run it.

**Comment by vsingh-msys** [comment]
Hi @bby-bishopclark,

Yes in knife-windows 3+ version it requires chef-15 we have moved windows node bootstrapping features from knife-windows to chef-15 [see here](https://github.com/chef/knife-windows#knife-bootstrap-windows-sshwinrm). I would recommend you to move a chef-15  as a couple of performance improvements for [more detail..](https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#chef-infra-client-150293) 

but if you want to say chef-14 no issue at all you can use knife-windows 1.9+ version.

Let us know further if you have any query?

Thanks!

**Comment by bby-bishopclark** [comment]
The license on chef-15 is an issue.  We are considering migrating off if it can't be fixed.

I'll try knife-windows 1.9 and hope it has everything I need.  Thanks!
