### ISSUE TITLE
session_opts[:operation_timeout] should be configurable

### ISSUE THREAD

**Issue by jmorenobl** [chef/knife-windows#88]
Hello, I'm in a case in which an installation takes ~40minutes but after 30min I get an http error 500.

I think it could be good if an user could change that parameter if necessary.

**Comment by carpnick** [comment]
This will be configurable once 1.0 comes out:
https://github.com/chef/knife-windows/blob/master/lib/chef/knife/winrm_base.rb#L110

**Comment by cheeseplus** [comment]
Closing this one as it was resolved long ago.
