### ISSUE TITLE
[KNIFE-379] Quote encoding error when bootstrapping windows from osx 

### ISSUE THREAD

**Issue by juliandunn** [chef/knife-windows#89]
Symptom: #39; characters show up during bootstrapping, therefore corrupting the bootstrap script (single quotes are replaced with this)

Solution: There is an unreleased patch to the WinRM gem that fixes this. We should update the gemspec to depend on the newer version when it's released. https://github.com/WinRb/WinRM/pull/73

**Comment by cheeseplus** [comment]
Closing old resolved issues, please open a new issue with current versions of the software if experiencing the same behaviour.
