### ISSUE TITLE
Can't seem to get kerberos to work

### ISSUE THREAD

**Issue by stonith** [chef/knife-windows#99]
I'm using the command knife winrm -m 'hostname' 'ipconfig' -R 'EXAMPLE.LOCAL' and receiving the following error: https://gist.github.com/stonith/70478f2171ec58291f33

If I use the winrm ruby gem on the same system, kerberos auth works properly.

**Comment by sneal** [comment]
This is likely fixed in winrm 1.3+ via https://github.com/WinRb/WinRM/pull/57

**Comment by cheeseplus** [comment]
Closing old resolved issues, please open a new issue with current versions of the software if experiencing the same behaviour.
